print("Hola clase. Estamos con git")
print("Espero que esteis aprendiendo mucho")
print("He añadido una tercera linea a este fichero Debe de quedar registrada")
print("Voy a añadir una cuarta linea al ficherito")
print("Añado esta linea para comprobar que trabajamos en local y se subirá al github mas tarde")
print("añadao una sexta linea. A ver si pasa a github, a la nube")
